In [6]:
def sum(a,b,c,d,e,f):
    return a+b+c+d+e+f
sum(5,8,2,4,7,9)

35

In [8]:
def multiply(a,b,c,d,e):
    return a*b*c*d*e
multiply(4,3,5,6,2)

720

In [18]:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)
np.sort(array_hw, axis=None)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


array([[5, 5, 8, 8, 8, 9],
       [3, 5, 5, 7, 7, 7],
       [2, 4, 6, 7, 8, 8],
       [1, 3, 4, 7, 9, 9]])

In [30]:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)
np.sort(array_hw, axis=0)
print("")
print(np.sort(array_hw, axis=0)[...,1])

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

[5 7 7 9]


In [31]:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)
np.sort(array_hw, axis=1)
print("")
print(np.sort(array_hw, axis=1)[2,...])

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

[2 4 6 7 8 8]


In [35]:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)
print("")
print(array_hw[1:,...])

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

[[7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [34]:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)
print("")
print(array_hw[...,2:])

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

[[8 8 9 8]
 [5 3 5 7]
 [8 4 2 6]
 [7 3 1 4]]


In [36]:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [37]:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)
print('')
print('Element sliced from third row and fourth column:')
print(array_hw[2,3])

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]

Element sliced from third row and fourth column:
4


In [38]:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)
print('')
array_hw.sum()

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]



145